version: '4'
services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "11433:1433"
    environment:
      SA_PASSWORD: "@Dn12345678"
      ACCEPT_EULA: "Y"

  API:
    image: 'springboot-databases-docker:latest'
    ports:
      - "8888:8080"
    depends_on:
      - sql-server-db
